apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: x8bkz2ybe-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:ae7742e23b70ff3ba429397d1a4bc2e4f17750e4@sha256:6b707d3144a9552b9857f531255d2496cfd0bc7fa506807c5bacc6164bb9c6d4
          name: container-image
